version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: /difftest
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: ubuntu
        update-types: [version-update:semver-major]
