/**
 * Regenerate src/shell/real-options.js: the options each real program
 * accepts, read from its --help in the reference container (man-db's apropos
 * and whatis from the host, since the minimized container has no man-db).
 *
 * Usage: node difftest/real-options.js
 * Needs Docker and the shellcraft-difftest image (node difftest/run.js builds it).
 */

import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

const IMAGE = 'shellcraft-difftest';
const IN_CONTAINER = [
  'cat', 'cp', 'mv', 'mkdir', 'rm', 'rmdir', 'touch', 'grep', 'id', 'uname', 'who', 'whoami', 'ls', 'dir', 'tree', 'sort', 'uniq', 'wc', 'head', 'tail',
  'pgrep', 'pkill', 'killall',
];
const ON_HOST = ['apropos', 'whatis'];
const SEPARATOR = '\u001eNEXT\u001e';
const OUT = path.resolve(import.meta.dirname, '..', 'src', 'shell', 'real-options.js');

/**
 * Read the options a --help text lists: every word starting with a dash at
 * the start of an indented line, and the letters of a `[-abc]` usage group.
 *
 * @param {string} help The --help output.
 * @returns {{short: string, long: string[]}} The short letters and the long names.
 */
export function optionsIn(help) {
  const short = new Set();
  const long = new Set();
  for (const line of help.split('\n')) {
    const spec = /^\s+(-[^\s,]+(?:,?\s*-[^\s,]+)*)/.exec(line)?.[1] ?? '';
    for (const word of spec.split(/,\s*|\s+/)) {
      const longName = /^(--[A-Za-z0-9][\w-]*)/.exec(word);
      const shortName = /^-([A-Za-z0-9?])(?![\w-])/.exec(word);
      if (longName) long.add(longName[1]);
      else if (shortName) short.add(shortName[1]);
    }
    for (const group of line.matchAll(/\[-([A-Za-z0-9]+)\]/g)) for (const letter of group[1]) short.add(letter);
  }
  return { short: [...short].sort().join(''), long: [...long].sort() };
}

function helpTexts(commands, run) {
  const script = commands.map(c => `${c} --help 2>&1; printf '${SEPARATOR}'`).join('; ');
  const r = run(script);
  if (r.status !== 0) throw new Error(`reading --help failed: ${r.stderr}`);
  return r.stdout.split(SEPARATOR).slice(0, commands.length);
}

function main() {
  const inDocker = script => spawnSync('docker', ['run', '--rm', '--network', 'none', '--name', `${IMAGE}-options-${process.pid}`, IMAGE, 'bash', '-c', script], { encoding: 'utf8' });
  const onHost = script => spawnSync('bash', ['-c', script], { encoding: 'utf8' });
  const texts = [...helpTexts(IN_CONTAINER, inDocker), ...helpTexts(ON_HOST, onHost)];
  const table = Object.fromEntries([...IN_CONTAINER, ...ON_HOST].map((name, i) => [name, optionsIn(texts[i])]));
  const body = Object.entries(table).map(([name, { short, long }]) => `  ${name}: { short: '${short}', long: ${JSON.stringify(long).replace(/"/g, "'").replace(/','/g, "', '")} },`).join('\n');
  writeFileSync(OUT, `/**
 * The options each real program accepts on Ubuntu 24.04, read from its
 * --help. Generated by difftest/real-options.js; regenerate, do not edit.
 */

/** @type {Readonly<Record<string, {short: string, long: string[]}>>} */
export const REAL_OPTIONS = Object.freeze({
${body}
});
`);
  console.log(`wrote ${OUT}`);
}

if (process.argv[1] === import.meta.filename) main();
